# Generated by Django 4.2.6 on 2023-10-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('is_important', models.BooleanField(blank=True, default=False)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
