version: "3.9"

services:
   app:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: appc
    volumes:
      - ./todoapp:/app
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=5432
      - DEBUG=${debug}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db

   db:
    image: postgres:13-alpine
    container_name: dbc
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
   todo-db-data:
