version: "3.9"

services:
   app:
    image: todo-postgres:latest
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: appc
    volumes:
      - ./todoapp:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - PORT=5432
    depends_on:
      - db

   db:
    image: postgres:13-alpine
    container_name: dbc
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
   todo-db-data:
