apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-todo
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /todo-app